site_name: Endstone
site_url: https://https://endstone.readthedocs.io/
site_author: Vincent Wu

repo_name: EndstoneMC/endstone
repo_url: https://github.com/EndstoneMC/endstone
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2023 - 2024 Vincent Wu

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EndstoneMC
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/endstone
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/endstone
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/endstone_mc

  version:
    provider: mike

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: EndstoneMC/endstone
      branch: main
  - mkdocstrings:
      handlers:
        python:
          paths: [ python/src ]
          options:
            annotations_path: brief
            show_bases: false
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_heading: true
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            inherited_members: true

theme:
  name: 'material'
  custom_dir: docs/overrides
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started.md
  - Reference:
      - reference/index.md
      - Python:
          - reference/python/index.md
          - Actor: reference/python/actor.md
          - Command: reference/python/command.md
          - Event: reference/python/event.md
          - Permissions: reference/python/permissions.md
          - Plugin: reference/python/plugin.md
          - Scheduler: reference/python/scheduler.md
  - Changelog: changelog/index.md
