[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "endstone"
authors = [
    { name = "Vincent Wu", email = "magicdroidx@gmail.com" }
]
description = "Endstone offers a plugin API for Bedrock Dedicated Servers, supporting both Python and C++."
readme = "README.md"
requires-python = ">=3.9"
keywords = ["plugin", "python", "minecraft", "bedrock"]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
]
dependencies = ["click", "requests", "rich", "tomli", "packaging"]
dynamic = ["version"]

[project.optional-dependencies]
test = ["pytest"]

[project.urls]
#Changelog = "https://endstone.readthedocs.io/en/latest/changelog.html"
Discussions = "https://github.com/orgs/EndstoneMC/discussions"
Documentation = "https://endstone.readthedocs.io"
Homepage = "https://github.com/EndstoneMC/endstone"
Issues = "https://github.com/EndstoneMC/endstone/issues"

[project.scripts]
endstone = "endstone._internal.bootstrap:cli"

[tool.scikit-build]
cmake.args = ["-G Ninja", "--preset conan-release"]
cmake.define = { BUILD_TESTING = "OFF" }
wheel.packages = ["endstone_python/python/endstone"]
wheel.license-files = ["LICENSE"]
install.components = ["endstone_wheel"]
install.strip = false
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
sdist.include = ["endstone_python/python/endstone/_internal/version.py"]

[tool.setuptools_scm]
write_to = "endstone_python/python/endstone/_internal/version.py"
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"

[tool.cibuildwheel]
build = ["cp*-win_amd64", "cp*-manylinux_x86_64"]
test-requires = "pytest"
test-command = "pytest {project}/endstone_python/test"
manylinux-x86_64-image = "ghcr.io/endstonemc/manylinux2014_x86_64:latest"

[tool.cibuildwheel.windows]
before-build = [
    "pip install conan",
    "conan profile detect --force",
    "conan export third_party/pybind11",
    "conan export third_party/funchook --version 1.1.3",
    "conan install . --build=missing -s compiler.cppstd=17 -c tools.cmake.cmaketoolchain:generator=Ninja",
    ".\\build\\Release\\generators\\conanbuild.bat"
]

[tool.cibuildwheel.linux]
before-build = [
    "pip install conan ninja",
    "conan profile detect --force",
    "conan export third_party/pybind11",
    "conan export third_party/funchook --version 1.1.3",
    "conan install . --build=missing -s compiler.cppstd=gnu17 -s compiler.libcxx=libc++ -c tools.cmake.cmaketoolchain:generator=Ninja"
]