name: Endstone CI (Linux)

on:
  push:
    branches:
      - next
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu16.04, ubuntu18.04 ]
        gcc_version: [ '7', '8', '9', '10', '11' ]
        build_type: [ Debug, Release ]

    name: Build on ${{ matrix.os }} (${{ matrix.build_type }}) with GCC ${{ matrix.gcc_version }}
    runs-on: ubuntu-latest
    container:
      image: conanio/gcc${{ matrix.gcc_version }}-${{ matrix.os }}
      options: --user root

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade conan cmake ninja

      - name: Build with Conan
        run: |
          conan profile detect --force
          conan create . --build=missing -s compiler.cppstd=17 -s build_type=${{ matrix.build_type }}